### ISSUE TITLE
unrelated

### ISSUE THREAD

**Issue by bcube2** [mfo13/mfo13.github.io#10]
Unrelated to this project, but I am going to post it anyway because you might be interested in knowing that.

This is how I see your web page by default: 

![marccelo_desktop](https://github.com/mfo13/mfo13.github.io/assets/12406850/2240bfd1-2a4b-408d-9a18-1d26e7e452b6)

If zoomed out to 90%, I can see the button bar. If zoomed in to 110%, I can see the button bar. But for default 100% zoom it is kind of annoying to use sliders.

This is how I see your web page in a mobile landscape mode by default:

![marcelo_mobile](https://github.com/mfo13/mfo13.github.io/assets/12406850/9dbfb0da-cc20-4ec9-9c04-84d4bdd8f263)

Another issue I noticed is that while the English version button in the main site is working fine, the English version link in the side menu is still requiring to log in into google account.

**Comment by mfo13** [comment]
Yes. This is the anoying atomatization of google... I'm always fixing such things because they change some parameter... Actually I should move to a real website hosting... I'was planing transfer it to versel but it was so much things to transfer and set that I quit... Anyway the website is not so visited since most of cubers are not interested on that way of playing. But, thank you for telling me!  I'll fix those things and stay in google.

**Comment by mfo13** [comment]
I think I have fixed the annoying scroll bars in my website. If you could check I would appreciate. :)

**Comment by bcube2** [comment]
I will use this thread/issue for things unrelated to your config tool in this repo :-)

As discussed earlier, I have edited the home page. Please let me know if I missed something or you are not OK with:

1. added you to the top of the homepage (you are in a great company there :-) )
2. added a new paragraph to the "Show AnimCubeJS evolution" dropdown button
3. added you to the LICENCE.md
4. in the Parameters section, I switched the order of links => now your config tool is being linked to before the other tool

Changes can be seen at https://github.com/bcube2/test5 / https://bcube2.github.io/test5/animcubejs.html

**Comment by bcube2** [comment]
> I think I have fixed the annoying scroll bars in my website. If you could check I would appreciate. :)

For landscape mode on mobile phone (tested in Samsung Internet browser and mobile Chrome), nothing changed. Since there are no sliders displayed, I can not see the button bar at all. Therefore, the simulator is useless :-(

As for desktop browsers (tested on FF and Chrome), now I can enjoy both the site and the simulators :-)
However, for zoom bigger than 140% I can not still enjoy the simulators in both FF and Chrome :-(
Btw. I know at least 2 people using 150% or bigger zoom by default.

**Comment by mfo13** [comment]
I think it is much better now. Not perfect but much better. Thank you.

**Comment by mfo13** [comment]
Thank you for helping with this topic. I'll close this issue.

**Comment by bcube2** [comment]
At first I thought [this reaction](https://github.com/mfo13/mfo13.github.io/issues/10#issuecomment-1915799772) was to [this post](https://github.com/mfo13/mfo13.github.io/issues/10#issuecomment-1914095867) but now I am not sure whether it is for [this post](https://github.com/mfo13/mfo13.github.io/issues/10#issuecomment-1914114008).

In any case, ACJS homepage has been updated, and simulators on your website are looking good for mobile landscape mode on my device now.

**Comment by mfo13** [comment]
Nice! Thank you for your help! Appreciated that! Even though visitors to my website are rare. :)

**Comment by bcube2** [comment]
Just for the record, this is how I see it now, with the same setup as on the previous pictures (first mobile, then desktop):

![marcelo](https://github.com/mfo13/mfo13.github.io/assets/12406850/0ad37e12-f005-4940-ba56-79b616239696)

![marcelo2](https://github.com/mfo13/mfo13.github.io/assets/12406850/710c8c6e-fa9a-4353-a8ac-084f4b9160f6)

**Comment by mfo13** [comment]
Well, unfortunately animcubeJS can not adjust the font size automatically, thus mobiles clip some figure titles... That would be an improvement for animcube but I have no idea how to do that...

**Comment by bcube2** [comment]
From the move parameter section: "Much more text can be made to fit by increasing the simulator width (see the examples in the [Using Simulator in Web Pages](https://animcubejs.cubing.net/animcubejs.html#usage) section) or reducing text size using the [textsize](https://animcubejs.cubing.net/animcubejs.html#textsize) parameter."

**Comment by mfo13** [comment]
Yes. But notice that the font size doesn't scale with the device screen. Check ,for example, in your cell phone in portrait position and then in landscape. Everything in the animcube drawing is correctly scaled unless the font size. It should be implicit but it is not. Perhaps that's because the animcube script is not drawing the font but using text printing. I'm thinking in a way of detecting the screen size and thus passing the proper font size scale by the textsize parameter or some other direct javascript interection with the cube that Feather has introduced, but I did not figure out yet...

**Comment by bcube2** [comment]
Oh, I see. Button height behaves the same - just change the window width for [responsive cubes](https://animcubejs.cubing.net/sources/codes/enhancement/responsive-cubes.html). I am sure I had a discussion with Michael about that but can´t remember its outcome yet :-)

**Comment by mfo13** [comment]
Nice! I'll check that, perhaps that is the solution! Thanks!

**Comment by mfo13** [comment]
Just to let you know. I tried the approach from animcube docs but the result was the same. Considering the docs code is more complicated I think I'll stick to `<div style="position:relative; width:100%; height:100%;">` which is simple and works the same. I still can't understand why the font-size doesn't scale properly... I've also tryied javascript approachs to detect the screen size and make a calculation to set directly the font in animcube parameter, but did not work either, same result....

**Comment by bcube2** [comment]
> I still can't understand why the font-size doesn't scale properly...

I can´t help you with that, but if it is not obvious from the JS code, perhaps it will be more obvious from the original java code? https://github.com/cubing/AnimCubeJS/blob/gh-pages/old/sources/AnimCube/AnimCube.java

If not, Josef/Michael would know for sure.

**Comment by bcube2** [comment]
> From the move parameter section: "Much more text can be made to fit by increasing the simulator width (see the examples in the [Using Simulator in Web Pages](https://animcubejs.cubing.net/animcubejs.html#usage) section) or reducing text size using the [textsize](https://animcubejs.cubing.net/animcubejs.html#textsize) parameter."

This part is not in the documentation anymore because text comments on multiple lines are now supported.

> I still can't understand why the font-size doesn't scale properly...

See how it works in [this post](https://github.com/cubing/AnimCubeJS/issues/43#issuecomment-2336814193). I think the new feature is solving your problem with longer text comments.

**Comment by mfo13** [comment]
Hello. Very nice! So Michael Feather has solved the issue with text scaling. I'll update the website when I have the time. Thank you for telling me.

**Comment by bcube2** [comment]
No problem, updating the JS file should do the trick :-)

If you want to have your cubes fancy, check out rounded corners: https://animcubejs.cubing.net/sources/codes/enhancement/florian.html - we have been thinking about making a new parameter for rounded corners, but decided to not add it (at least not right now).

**Comment by mfo13** [comment]
Wow! Nice, it is evolving! When I have the time I'll make the updates, the website is not so visited anyway. Thank you to let me know.
