### ISSUE TITLE
upgrade to latest scripts

### ISSUE THREAD

**Issue by bcube2** [mfo13/mfo13.github.io#11]
Please upgrade to the latest ACJS scripts. Unless a bug is found, they should hold for a while.

**Comment by mfo13** [comment]
OK. Done. All my mirrors were upgraded. Thank you. I've sent you the last modifications in config_tool.

**Comment by bcube2** [comment]
Cool, thank you for upgrading.

I don´t know where did you send the last modifications in config_tool to :-). But it doesn´t matter, I can download it from this repo.

**Comment by mfo13** [comment]
Oh! OK. I'll make the last changes you asked for. Download when you think it is time to upgrade. Thanks.
