### ISSUE TITLE
delete id=cube?

### ISSUE THREAD

**Issue by bcube2** [mfo13/mfo13.github.io#12]
As an amazing beginner-friendly tool, assume a newcomer will be linked to your config tool.

The newcomer will see 

```
<script>
AnimCube3("id=cube");
</script>
``` 

in the HTML code below the simulator. So he/she will be asking "hmm, I don´t know what id parameter does, let´s see ACJS documentation to find it out". Even though it is decribed there, it is in a not-so-beginner-friendly Enhancement section.

Also, in the Using Simulator in Web Pages section it is written "Every parameter is optional so the simplest possible call is made using <script>AnimCubeX("")</script> (i.e. with no parameters at all)."

Would you consider to remove id=cube from the HTML code below the simulator to show only

```
<script>
AnimCube3("");
</script> 
```

by default?

**Comment by mfo13** [comment]
Well I prefer to keep this way because the user can realize that it is possible to place many cubes in the same page. The way the config_tool presents the html code to the user makes it necessary the identification: id=cube. Only if the script tags are put inside the div tags the  id=cube is not necessary. But since the script block is presented outside the div tags the id=cube is necessary. I think it is a better way of organazing the code. For example, suppose the user wants 3 cubes in a table, like bellow:

```
<table>
   <tr>
       <td>
            <div id="cube_1"></div>
       </td>
       <td>
            <div id="cube_2"></div>
       </td>
       <td>
            <div id="cube_3"></div>
       </td>
    </tr>
</table>

<script>
AnimcubeX("id=cube_1&many parameters here .................................. ........................... .
....................... ............................... .................... .......... ....... ... ................................ ........................ ................................. .......................... ....................... ....");
AnimcubeX("id=cube_2&many parameters here .................................. ........................... .
....................... ............................... .................... .......... ....... ... ................................ ........................ ................................. .......................... ....................... ....");
AnimcubeX("id=cube_3&many parameters  here.................................. 
........................... ........................ ............................... .................... .......... ....... ... ................................ ........................ ................................. .......................... ....................... ....");
</script>

```

**Comment by bcube2** [comment]
I get your point.  Yet I think there is a chance I didn´t make myself clear so let me explain.

I would like to keep things as simple as possible, especially for newcomers. If a newcomer reaches the Parameters section, he will see your config tool even before he reads through the Parameters section to get familiar with the parameters.

I am asking for commenting out id="cube" only from what he sees in your config tool page, not what is written in your source code to make your config tool functional.

As I understand it, div id="cube" can be used mainly for advanced functionality like creating your config tool or stuff mentioned in the Enhancement section. But it is not necessarry for newcomers/beginners. 

In the Parameters section, there are a lot of simulators. None of them is using id unless they use advanced stuff like a show/hide button. 

Since <script>AnimcubeX("id=cube_1&many parameters here...")</script> will do  the same thing as <script>AnimcubeX("many parameters here...")</script> in terms of functionality for a single simulator, I would prefer to comment out id="cube" parts from what he sees in your config tool site. 

Then again, I understand your reasoning, I just thought it was not necessarry to tell a newcomer. I know I would be frustrated if I knew nothing about HTML and seeing some parts of a HTML code not knowing what it does (especially if it looks like it is just another parameter supported by the ACJS script).

As I see it, newcomers/beginners don´t need to know, advanced HTML/JS users will know it anyway so no need to tell them either.

**Comment by mfo13** [comment]
OK. I understand your point of view and agree. You are right, if a newcomer decides to go more deep in configuration of course he will find such information out there including by inspecting the code of the config_tool itself. I'll make the showing code as simple as possible.

**Comment by mfo13** [comment]
id=cube deleted. I made the html code look as simple as possible, actually when fully default you just need AnimCubeX().

**Comment by bcube2** [comment]
2 more things and I will stop nagging you, I promise :-)

1) could you please add double quotation marks and delete those semicolons so that it would look like this by default (to be in accordance with the ACJS doc)?
```
<script>
AnimCubeX("")
</script>
```
2) Oh, seems you already fixed that missing space between script and div tags when hitting the refresh button while I was typing, so nevermind this second point

**Comment by mfo13** [comment]
OK. Never mind, you are not nagging (this word is new for me), you are improving the tool for the users. Michael Feather is right! You are damn good in finding bugs in these things :))

**Comment by mfo13** [comment]
Done! I think now it is the way you expect a newbie to see.
