### ISSUE TITLE
unify yz terminology?

### ISSUE THREAD

**Issue by bcube2** [mfo13/mfo13.github.io#13]
All parameters in your config tool are labelled in accordance with the ACJS doc except for yz (which is labelled as "switch yz" in your tool).

To avoid confusion (a user might look up for a "switch yz" parameter in the ACJS doc) and to unify terminology, would you consider to rename "switch yz" to "yz" in your tool?

**Comment by mfo13** [comment]
OK. I put "switch" in front because yz was too short. I'll do that.

**Comment by mfo13** [comment]
Done!
