### ISSUE TITLE
default checkbox vs dropdown button for numeral parameter values

### ISSUE THREAD

**Issue by bcube2** [mfo13/mfo13.github.io#14]
Not really an issue (I would say it doesn´t bother anybody), just an FYI: while there is a default dropdown button for the buttonbar parameter (which have numeral parameter values), there are default checkboxes for the movetext and borderwidth parameters (which also have numeral parameter values).

If you want to unify them go ahead. If you want to keep them as they are that is also fine. :-)

**Comment by mfo13** [comment]
Well, the problem here is that not all defaults are really defaults. Somo defaults are constant, they are not dependent of other things. The "defaults" with checkboxes are those that change deppending on other parameters. That's why some kind of control is needed, so the script knows whether the user don't bother about the "automatic defaults".

**Comment by bcube2** [comment]
Hmm, I was talking about parameters with numeral values: buttonbar, movetext and borderwidth. All 3 these parameters are dependant on parameter´s settings, namely:

buttonbar - move, scramble
movetext - sign, wca
borderwidth - supercube, gabbacolors

**Comment by mfo13** [comment]
You see... I did not figure out a better idea. If you think in something let me know.

**Comment by bcube2** [comment]
> You see... I did not figure out a better idea. If you think in something let me know.

You lost me here :-)

I was only pointing out that there are 3 "similar" parameters, and 2 of them are designed with a checkbox while the other one with a dropdown button by defualt. I was also saying it doesn´t bother anyone in my opinion (that they don´t all use the same default design, because they could).

It is not really an issue, more like an esthetic preference (which could be unified, but also could be kept as is now).

**Comment by mfo13** [comment]
Sorry, I was lost, I'll check that.

**Comment by mfo13** [comment]
OK. So you found another bug. Notice that when you choose scramble=1, buttonbar=1 is not necessary, correct? But if select on porpose buttonbar=1 it appers in the command line. So, the best option is the checkbox, because the user don't see the default, unless he uncheck the box. Moreover I need to put this if condition in the code, if scramble=1 and buttonbar=1 then buttonbar is not needed in the command line.

**Comment by bcube2** [comment]
Well, it may differ from person to person, but personally, I don´t see that as a bug. Just because a user set redundant settings (and yes, it will happen a lot in my opinion) doesn´t mean the simulator won´t be shown properly.

By that logic, a declaration of two identical settings (not possible in your config tool, but possible offline) would be a bug (exemple: snap=1&snap=1). Or a declaration of non-existing parameter value would be a bug (example: initmove=g). No, I don´t see these as a bug because the simulator will still be fully operational.

Also, buttonbar=1 alone might be considered as a misusage of the simulator ;-)

But I get your point, our definition of "bug" is just different and it´s completely fine.

**Comment by mfo13** [comment]
Well, I'm not a programmer just a hobbist. Thank you for clarify that point. You said it better, it is a misusage. That's why we still need to fix it in order to appear as clear as possible for a newbie.

**Comment by mfo13** [comment]
I think it is ok now. I've place a checkbox and the conditions for the command line. Check, please.

**Comment by bcube2** [comment]
> Well, I'm not a programmer just a hobbist. Thank you for clarify that point. You said it better, it is a misusage. That's why we still need to fix it in order to appear as clear as possible for a newbie.

As stated in another issue thread, I personally would be hesitant to cover these reduntant user settings. Look at the scramble parameter description. It might make your source code a little bit bloated to cover the move, initmove, initrevmove, demo, facelets and superfacelets settings when declaring the scramble parameter.

After all, it is already written in the ACJS doc that these will be ignored. But go ahead with whatever approach you find best, just please be consistent with it :-)

Edit: unless your source code is super duper fancy and overly robust, I don't think you can really cover reduntant / misusing user inputs like move=q or movetext=8 (I can type that value by using numerical keyboard).

**Comment by bcube2** [comment]
> I think it is ok now. I've place a checkbox and the conditions for the command line. Check, please.

Looks good to me.

**Comment by mfo13** [comment]
Nice! I think we can close this issue.

**Comment by bcube2** [comment]
Well, by 

> Look at the scramble parameter description. It might make your source code a little bit bloated to cover the move, initmove, initrevmove, demo, facelets and superfacelets settings when declaring the scramble parameter.
After all, it is already written in the ACJS doc that these will be ignored. But go ahead with whatever approach you find best, just please be consistent with it :-)

I tried to imply that you are not being consistent. While for the scramble=1&buttonbar=1 setting only the scramble=1 setting is being shown to the user, for the scramble=1&move=R setting the scramble=1&move=R setting is being shwon to the user. Both buttonbar and move settings are redundant in these cases, but you treat them differently (and I asked for treating them the same way).

But I guess leaving it as is now is also fine.

**Comment by mfo13** [comment]
Yes. I think you are right, it is going to be a mess if I try to cover all redundant possibilities, and that's why, in fact, I'm using the default option, to let the user freely set up things even if they are redundant. I'll review this logic in the code and move back to the previous approach instead of trying to guess what the user wants.

**Comment by bcube2** [comment]
While reviewing, could you please keep the functionality for the wca/sign and facelets/colorscheme parameters? That is, if one is declared, the other one can not be declared too (because they are mutually exclusive).

**Comment by mfo13** [comment]
Well... It is working for me. Are you sure you have checked the last version of the code?

**Comment by bcube2** [comment]
I was reffering to your 

> it is going to be a mess if I try to cover all redundant possibilities

and 

> I'll review this logic in the code and move back to the previous approach instead of trying to guess what the user wants.

If I understood you correctly, I thought you are going to display buttonbar=1&move=R as buttonbar=1&move=R instead of only move=R (and similarly for other redundant settings). I am not sure what logic implementations you want to revert exactly, so I asked whether you can keep the logic for wca/sign and facelets/colorscheme (because before your logic implementations they used to work like this: https://animcubejs.cubing.net/sources/codes/enhancement/parameters/config_tool.html)

**Comment by mfo13** [comment]
I did not review yet. But the our decision was keeping the default boxes. I'll just review the logic of the output.

**Comment by mfo13** [comment]
Stripped out the output logic with:
buttonbar/move/scramble;
borderwidth/supercube/gabbacolors ;
movetext/sign/wca;
yz/sign/wca.;
when such parameters are not default.
The logic between facelets and colorscheme was kept as it was.

**Comment by bcube2** [comment]
For sign=1 the yz=0&sign=1 is outputed. Similarly for wca=1

Edit: whatever setting seems to be triggering the yz=0 setting being added to the output.

**Comment by mfo13** [comment]
Ops... remnants of that output logic... I'll check.

**Comment by mfo13** [comment]
Done. I put 0/1 for yz since on/off doens't make sense anymore. Notice that if the user unselect the default yz then this parameter will be set despite anything else. I just kept the mutual exclusivity of sign/wca and the mutual exclusivity of facelets/colorscheme.

**Comment by mfo13** [comment]
Nice! So now I think this issue is closed.
