### ISSUE TITLE
gabbacolors for 4x4x4 - 7x7x7

### ISSUE THREAD

**Issue by bcube2** [mfo13/mfo13.github.io#15]
For 4x4x4 - 7x7x7 the gabbacolors options stopped working untill you click on something else.

1) Select a 4x4x4, turn gabbasoft on, turn snap on - this will turn on gabbacolors but you can not turn it off unless clicked on something else (e.g. edit off)

Refresh page

2) Select a 4x4x4, turn gabbasoft on, click on facelets default - this will turn on gabbacolors but now you can turn it off and on freely

Refresh page

3) Select a 4x4x4, turn gabbasoft on, click on colors default - this will turn on gabbacolors but you can not turn it off unless clicked on something else (e.g. edit off)

**Comment by mfo13** [comment]
Annoying bug this one... Found and fixed!
