### ISSUE TITLE
scw missing

### ISSUE THREAD

**Issue by bcube2** [mfo13/mfo13.github.io#16]
Where did scw go if turning supercube on?

**Comment by mfo13** [comment]
Well, it should appear... I'll check, perhaps I've messed the thing when fixing the gabbacolors bug...

**Comment by mfo13** [comment]
SCW working again. I placed it close to colors, I think it makes more sense. Notice it appears only if you select supercube on.

**Comment by bcube2** [comment]
> SCW working again.

Yaaaay, thank you.

> Notice it appears only if you select supercube on.

I knew that :-P
