### ISSUE TITLE
Facelets pallete not visible

### ISSUE THREAD

**Issue by bcube2** [mfo13/mfo13.github.io#2]
Hi,

while playing with your configuration tool, I noticed 2 minor bugs:

1) when selecting Faces -> facelets -> Pallete/color "4" for the front center sticker,  then selecting Cube Setting -> supercube on, the pallete for facelets is no longer visible

2) from a point above if the page is refreshed, notice how supercube option is still on (while the simulator does not contain a supercube parameter). When now selecting Faces, I can see the facelets option is not checked as default (even though the simulator says otherwise), so when clicking the facelets default option, suddenly the supercube option is triggered (which is kind of understandable but might look odd to some users)   

P.S. please let me know if you are not OK with the changes I made at https://animcubejs.cubing.net/animcubejs.html (I included you in the "Show AnimCubeJS evolution" dropdown in the Introduction section, added a link to your web-site and mentioned Michael in "The 7x7x7 cube was contributed by [Marcelo Falcão de Oliveira](https://sites.google.com/site/cubomagicosemdecoreba/home) (in collaboration with Michael Feather)." and added a favicon in https://animcubejs.cubing.net/sources/codes/enhancement/parameters/config_tool.html to be consistent with other ACJS pages).

**Comment by mfo13** [comment]
Hello! I've been absent. Will check that!

**Comment by mfo13** [comment]
I agree! Thank you very much!

**Comment by bcube2** [comment]
> I agree! Thank you very much!

You got it all wrong, I should be thanking you ;-)

I will re-open this issue (well, it seems that only collaborators can do that which I am not) since I can replicate both points mentioned above. As for point 1., the pallete containing numbers 0-9 and letters like y, o, r, b, g, w is not visible.

As for point 2. - after hitting the refresh button I can see `<script>
AnimCube3("id=cube");
</script> ` written in the HTML code below the simulator, but when opening Cube Settings, I can see the supercube is still on. But if the user only checks Faces -> facelets back again, suddenly the simulator gets updated with the supercube=1 settings (even though the user didn´t change that after the page refresh). So I was asking whether this is preferred behavior.


P.S. to keep you updated (e.g. about the wca parameter and the movetext=6 setting) I sent you an e-mail some time ago. It had several links in it, so there is a chance it went straight to the junk folder.

**Comment by mfo13** [comment]
I think issue 1 was solved. Please check. I did not understand the issue 2, but perhaps it was solved as well.

Meanwhile, since you reopened this discussion I have a suggestion for the "AnimCubeJS evolution" history. In order to extend the code for 7x7x7 we were forced to find a correct geometrical solution for the workaround used to correctly hide some inner parts of the cube when twisting layers. This issue was affecting all the cubes but not well visible in the smaller ones. With this core issue fixed the view of moving parts is now correct for all cases, the code got a bit simpler and can be further extended for even bigger cubes like 8x8x8 and so on. I think it was an important improvement in the core of the code.

**Comment by bcube2** [comment]
> I think issue 1 was solved. Please check. I did not understand the issue 2, but perhaps it was solved as well.

Point 1 is solved now, thank you. 

For point 2, the situation I was afraid of happened. While for desktop Chrome and mobile Samsung Internet browser it is OK, for desktop FF I can still see `<script>
AnimCube3("id=cube");
</script> ` while supercube option being on and facelets option being unchecked.

P.S. thank you for telling me about the core improvement, I will edit the ACJS doc accordingly.

**Comment by mfo13** [comment]
I understand... Well, it will take some time until I discover why it is not working for desktop FF...

**Comment by bcube2** [comment]
From my experience, allowing users to refresh the page is a little bit dangerous. Not only there are several ways how to refresh the page (at least for desktop browsers), there may also be differences in what exactly is being refreshed among browsers.

To avoid these uncertainities, would you consider making a button which says Clear/Reset/Refresh/Null/Delete/whatever that would set the cube to its initial state (such as the Clear button at https://animcubejs.cubing.net/sources/codes/enhancement/parameters/create.html)?

**Comment by mfo13** [comment]
I've seen that firefox is automatically configured to let the user choose if he/she wants full or partial refresh of the page. If you want a full refresh press "shift" and thus click on refresh. I was looking for a command or so to tell the browser the page MUST have full refresh but without success yet... So I've placed a "Refresh page" buttom at the end of the menu bar as you sugested. Please test.

**Comment by bcube2** [comment]
"Refresh page" button working for me.
