### ISSUE TITLE
Parameters implicitly setting other parameters

### ISSUE THREAD

**Issue by bcube2** [mfo13/mfo13.github.io#3]
Hi,

turning on and off these parameters will leave another parameters set (I would expect no implicit parametets to be set when turning them off): supercube, sign, wca, gabbacolors

**Comment by mfo13** [comment]
Well. I thought the contrary. If the user have, for example, already have set many other parameters and try just to have a look in the supercube, should all the others be reset?

**Comment by bcube2** [comment]
> Well. I thought the contrary. If the user have, for example, already have set many other parameters and try just to have a look in the supercube, should all the others be reset?

Definitely not. I am talking about these kind of situations: if the user opens Cube Settings, checks supercube on, then checks it off, the HTML code below the simulator is saying "...borderwidth=6" - but that setting was not set by the user (it was implicitly set by the supercube=1 setting which is now off).

**Comment by mfo13** [comment]
I understand. Indeed there are some situations like this, but we need to make a decision regarding such cases. Taking your example, suppose that the user has already set border=6 and thus turns to supercube. Notice that the border=6 is automatically erased because the supercube setting. When the user go back to the normal cube the border=6 returns like it was previouly set. On the contrary if you automatically turns off such option the previous choice is now erased. Did you get my point? So, in one way or another, there will be an implicity setting. Off course we could make the code more elaborated to 'memorize' and workaround such situations but my question is, does it worth?

**Comment by bcube2** [comment]
My idea was to mimic this tool: https://animcubejs.cubing.net/sources/codes/enhancement/parameters/create.html. If you input "borderwidth=6&supercube=1" to that tool, the borderwidth=6 setting is redundant (however, that is not really a problem in my opinion). Now, if you input only "supercube=1", apply it and click on the Clear button, you will get the default cube state.

That is what´s expected in my opinion, because it will reflect the behavior when the user is setting parameters offline e.g. for his/her cube tutorial. By that I mean if he/she sets the supercube=1 setting, then he/she changes it to the supercube=0 setting, the default cube settings will be applied (without the borderwidth=6 setting).

Of course if it is too difficult to implement then forget it, your tool is amazing already :-). But hopefully you understand my point.

**Comment by bcube2** [comment]
> suppose that the user has already set border=6 and thus turns to supercube. Notice that the border=6 is automatically erased because the supercube setting.

This seems to be the problem between our approaches, because I am suggesting that if the user sets the borderwidth=6 setting first, and then it is followed by the supercube=1 setting, the HTML code under the simulator should display both these settings. Not only the supercube=1 setting which is your approach.

**Comment by mfo13** [comment]
I do understand your point and perhaps we could finda a suitbla solution. What about adding a default box for border, like we are using for cubecolor, for example? So, if the user uncheck the default box the explicit border number is kept anyway, on the other hand, with the default box checked the border parameter will be automatically implicit with the cube choice, normal or super. What do you think? I think it is easy to implement.

**Comment by mfo13** [comment]
I've implemented the above mentioned approach. Please test it. I think it is a fair solution.

**Comment by bcube2** [comment]
Working great for both the supercube and gabbacolors parameters, thank you.

Could you please implement similar functionality for the sign and wca parameters too?

**Comment by mfo13** [comment]
I'll do that for sign. Regarding wca I need to understand at first how you have implemented that. By the way why have you placed a wca check buttom instead of just using movetext 6? I did not get this point.

**Comment by bcube2** [comment]
Before the wca parameter was implemented, user could use either the default ACJS notation as described in the move parameter, or the sign notation as described in the sign parameter. With the wca parameter, user can now choose this notation as well. 

Suppose the user wants to animate an official 7x7x7 scramble from the WCA competition. Without the wca parameter the user would need to translate the moves to either the ACJS or sign notation first before animating. With the wca parameter, the moves can be pasted directly to the move parameter.

Movetext is displaying move sequences. You can write algorithms/scrambles in any of 3 supported notations and display them in any of those 3 supported notations.

**Comment by mfo13** [comment]
Well, I confess I did not get the logic of how movetext, sign and wca should work together.... Anyway, I've placed a default option in movetext thus nothing is atuomatically set if this default option is on. Plese check. If it is not working properly, please, try to explain me, with some examples, how this 3 parameters should work together as well as yz.

**Comment by bcube2** [comment]
Okay, sign and wca parameters are mutually exclusive - meaning that the user (I will use "you" instead of "user") should set either one or the other parameter, but not both at the same time. So far so good regarding your config tool.

So let´s turn sign on first. Select a 4x4x4. In the move textarea, type `x y z Rt`. On the simulator you can see `x y z r`, meaning both yz=1 and movetext=5 settings were implicitly set (so far so good). 

Now turn off sign and turn on wca parameter. You will get expected values too (yz=1 and movetext=6 implicit values). So far so good.

However, if you uncheck default movetext, you will get AnimCube4("id=cube&move=x y z Rt&movetext=0&yz=0&wca=1") instead of expected AnimCube4("id=cube&move=x y z Rt&movetext=0&wca=1") with implicit yz=1 (because of wca=1). The same applies for sign: you will get AnimCube4("id=cube&move=x y z Rt&movetext=0&yz=0&sign=1") instead of expected AnimCube4("id=cube&move=x y z Rt&movetext=0&sign=1") with implicit yz=1 (because of sign=1). As a result, moves 2 and 3 are not correct on the simulator.

So only the default checkbox for the switch yz option is needed in my opinion (as both the wca and sign parameters are implicitly setting the yz=1 setting).

**Comment by mfo13** [comment]
OK. So I'll revert to the previous configuration but placing a default box for switch yz, furthermore I need to make sign and wca mutally exclusive, when you set one the other is automatically unset.

**Comment by bcube2** [comment]
Well, maybe I didn´t make myself clear or you misunderstood me, because there is no need to revert, I was talking about addition to what you have already done... But I will see what you will come up with.

Personally, I would be hesitant to make parameters mutually exclusive in your config tool (see e.g. https://animcubejs.cubing.net/animcubejs.html#scramble what you would have to do in your code regarding mutual exclusivity), but go ahead if you like to.

**Comment by mfo13** [comment]
I've done the changes. Plese check if it is working like you expected.

**Comment by bcube2** [comment]
Let´s focus only on the sign parameter for a moment, ok? Turn on sign. Movetext should be set to 5. (yz setting as of now is OK)

**Comment by mfo13** [comment]
OK. So movetext is implicitly set to 5 with sign on. I suppose the same will happen with wca but now it is 6. Correct? I'll do that.

**Comment by bcube2** [comment]
Correct

**Comment by mfo13** [comment]
Done! Test please.

**Comment by bcube2** [comment]
We are getting there :-)

Turn sign on. Turn it off. AnimCube3("id=cube") should be displayed. This is the borderwidth/supercube kind of stuff, that is why movetext needs its default checkbox like you had before.

Other than that, it is working perfectly.

**Comment by mfo13** [comment]
Ok. So I'll put back the default on movetext. This means that we'll have default on both, yz and movetext.

**Comment by mfo13** [comment]
I think I've found an alternative way without adding another default box. Test please.

**Comment by bcube2** [comment]
Perfect, thank you.

My 2 cents:

1. now that you found a way to implicit settings right in the config tool (e.g. if sign is turned on, implicit movetext=5 is set), the default boxes for yz and borderwidth are not needed, right? Feel free to keep them if you like them or delete them if you don´t like them.
2. if you set other than default movetext value when sign/wca is on, the HTML code below the simulator is divided into more rows. Not sure if that´s a bug or a feature (tested for AnimCube3("id=cube&move=x y z Rt&sign=1&supercube=1") vs AnimCube3("id=cube&move=x y z Rt&movetext=6&sign=1&supercube=1")).

Edit: It is actually a little bit moe complicated than that. If you set movetext=1&sign=1, it should show movetext set to 1, not 5. But in your current config tool, it would make it impossible to switch from sign to wca (and vice versa), because it is implicitly setting movetext to 6, not 5 after switching. I would not be surprised if I lost you here, so I will provide examples:

Apply

movetext=1&
sign=1&
move=x y z Rt

to https://animcubejs.cubing.net/sources/codes/enhancement/parameters/create.html. Movetext=1 is displayed on the simulator. Change only sign=1 to wca=1 and apply changes. Movetext=1 (not movetext=6) is still displayed on the simulator.

I think the default checkbox for the movetext parameter could fix it.

**Comment by mfo13** [comment]
You see... there are many excludent combinations. I also think the default box is the best option. It is done. Please test it.

**Comment by bcube2** [comment]
Bravo. Thank you very much, no issue found.

**Comment by mfo13** [comment]
Nice! So I'll make this a final version, upload in my animcubejs fork and request a pull. The config improvement will take time so it is going to be another version.

**Comment by bcube2** [comment]
Well, I meant no issue found in this thread/issue to make myself clear :-)

Give me some time to find another questions/issues ;-)

Oh, and no stress, no timeline is given for your updates.
