### ISSUE TITLE
typo in movetext

### ISSUE THREAD

**Issue by bcube2** [mfo13/mfo13.github.io#4]
Hi,

when selecting cube size other than 3x3x3 and movetext other than 0 or 1 or 5, it says "don't work for this cube"  - shouldn´t it be "doesn´t work for this cube"? Or, perhaps better, "not supported for this cube size"?

**Comment by mfo13** [comment]
Yes, sure! Typo corrected. Now the message is: "not supported for this cube size". Thank you!
