### ISSUE TITLE
missing: wca parameter, movetext=6 setting

### ISSUE THREAD

**Issue by bcube2** [mfo13/mfo13.github.io#5]
Hi,

please add the wca parameter and the value of 6 for the movetext parameter.

**Comment by mfo13** [comment]
Hello! I've been absent. What is going on?

**Comment by mfo13** [comment]
Ok! Now I see, there is new movetext parameter (6) for wca moves. OK. I need some time to remember the logic behind the things... In Animcubejs docs it says that  movetext=2, movetext=3 and movetext=4 settings should be considered obsolete, do you think should I remove them from the config tool?

**Comment by mfo13** [comment]
Well. I noticed that you have already done this improvement in the config tool at the Animcube repository. Thank you! I'll just copy the script from there and paste here in this testing repository. I'll also update the animcube scripts here. Best regards!
