### ISSUE TITLE
issue no. 2

### ISSUE THREAD

**Issue by bcube2** [mfo13/mfo13.github.io#6]
Adding this placeholder here before I forget this issue: https://github.com/mfo13/mfo13.github.io/issues/2 is still open in my opinion.

**Comment by mfo13** [comment]
I think it was solved now. Please check my comments there.

**Comment by mfo13** [comment]
I think finally it is solved (not exactly like I wanted to, but solved). See my comments there.

**Comment by bcube2** [comment]
Ok, if that´s your final solution feel free to close this issue. If that´s a temporary solution I would prefer this issue to be open.

**Comment by mfo13** [comment]
I will try to find a solution for the browser refresh. I still prefer the page witout the refresh buttom. If you like it I can keep it, but together the browser refresh issue solved.

**Comment by mfo13** [comment]
After reading many documents and after many attempts, it appears that a full update cannot be forced for all browsers unless there is a refresh button that the user presses voluntarily. So I will keep the "refresh page" button and close this issue.
​

**Comment by bcube2** [comment]
Another way which comes to my mind is allowing users to edit the textarea below the simulator (so that the user could delete settings which are not needed anymore just like in his/her offline creating, and the simulator would be updated accordingly). But it opens door for breaking something else in your config tool I guess.

Since I don´t see a way how to cover cases like ctrl+R, the refresh button seems to be the best option by the process of elimination.
