### ISSUE TITLE
facelets vs colorscheme

### ISSUE THREAD

**Issue by bcube2** [mfo13/mfo13.github.io#9]
Not sure if bug or feature.

When turning off facelets default box, the colorscheme option disappears (which might be a good thing since they are mutually exclusive). 

Could it be done the other way around as well (when turning off colorscheme default box, the facelets option would disappear)?

**Comment by mfo13** [comment]
OK. Done! Test please.

**Comment by bcube2** [comment]
Excellent. Thank you.

**Comment by mfo13** [comment]
Good! Issue closed.
